version: "3.9"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - 127.0.0.1:5432:5432
    restart: on-failure
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}
