version: "3.9"

services:
  app:
    image: "ghcr.io/gabe565/limo"
    build: .
    environment:
      LIMOD_DB_HOST: database
      LIMOD_DB_USERNAME: limo
      LIMOD_DB_PASSWORD: limo
      LIMOD_DB_DATABASE: limo
    ports:
      - "80:80"
    volumes:
      - "./data:/data"

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: limo
      POSTGRES_PASSWORD: limo
      POSTGRES_DB: limo
    ports:
      - 127.0.0.1:5432:5432
    restart: on-failure
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}
