// Code generated by "stringer -type Output -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutputText-0]
	_ = x[OutputJson-1]
}

const _Output_name = "textjson"

var _Output_index = [...]uint8{0, 4, 8}

func (i Output) String() string {
	if i >= Output(len(_Output_index)-1) {
		return "Output(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Output_name[_Output_index[i]:_Output_index[i+1]]
}
